database:
  prod:
    host: shortlinks-db-server
    user: shortlinks-user
    password: shortlinks-password
    dbname: shortlinks
    port: 5432
    sslmode: disable
    timezone: UTC
  test:
    driver: sqlite
    dsn: ":memory:"
