server:
  host: shortlinks_host
  port: 8000
database:
  prod:
    host: shortlinks_db_host
    user: shortlinks_user
    password: shortlinks_password
    dbname: shortlinks_db
    port: 5432
    sslmode: disable
    timezone: UTC
  test:
    driver: sqlite
    dsn: ":memory:"
