# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Setup GOROOT
      run: export GOROOT=$(pwd)

    - name: Build
      run: go build -v go-shortlinks

    - name: Test
      run: export CONFIG_FILE=$(pwd)/config.yaml; go test -v ./tests/...
